### ISSUE TITLE
Authentication failed 

### ISSUE THREAD

**Issue by testica** [frankjdelgado/wiki-history-extractor-api#47]
I just follow the README steps and all is fine but when I want to use the api it throw an error. It happens when I fetch to GET /articles or GET /extract

Output when GET /articles
```
flask_1   | Traceback (most recent call last):
flask_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
flask_1   |     return self.wsgi_app(environ, start_response)
flask_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
flask_1   |     response = self.handle_exception(e)
flask_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
flask_1   |     reraise(exc_type, exc_value, tb)
flask_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
flask_1   |     response = self.full_dispatch_request()
flask_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
flask_1   |     rv = self.handle_user_exception(e)
flask_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
flask_1   |     reraise(exc_type, exc_value, tb)
flask_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
flask_1   |     rv = self.dispatch_request()
flask_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
flask_1   |     return self.view_functions[rule.endpoint](**req.view_args)
flask_1   |   File "/app/app/api_1_0/articles.py", line 30, in articles
flask_1   |     db = RevisionDB(config={'host': config['default'].MONGO_HOST, 'port': config['default'].MONGO_PORT, 'username': config['default'].MONGO_USERNAME, 'password': config['default'].MONGO_PASSWORD})
flask_1   |   File "/app/vendors/db_connector.py", line 20, in __init__
flask_1   |     if self.client.wiki_history_extractor.authenticate(config['username'], config['password']) == True :
flask_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/database.py", line 1048, in authenticate
flask_1   |     connect=True)
flask_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 505, in _cache_credentials
flask_1   |     sock_info.authenticate(credentials)
flask_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/pool.py", line 523, in authenticate
flask_1   |     auth.authenticate(credentials, self)
flask_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/auth.py", line 470, in authenticate
flask_1   |     auth_func(credentials, sock_info)
flask_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/auth.py", line 450, in _authenticate_default
flask_1   |     return _authenticate_scram_sha1(credentials, sock_info)
flask_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/auth.py", line 201, in _authenticate_scram_sha1
flask_1   |     res = sock_info.command(source, cmd)
flask_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/pool.py", line 419, in command
flask_1   |     collation=collation)
flask_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/network.py", line 116, in command
flask_1   |     parse_write_concern_error=parse_write_concern_error)
flask_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/helpers.py", line 210, in _check_command_response
nginx_1   | 10.0.2.2 - - [10/Nov/2017:04:48:32 +0000] "GET /api/v1/articles HTTP/1.1" 500 33483 "http://192.168.20.101:8080/api/v1/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36"
flask_1   |     raise OperationFailure(msg % errmsg, code, response)
flask_1   | OperationFailure: Authentication failed.
```
when GET /extract 
```
mongo_1   | 2017-11-10T04:53:49.351+0000 I ACCESS   [conn4] SCRAM-SHA-1 authentication failed for wiki on wiki_history_extractor from client 172.18.0.5:46008 ; UserNotFound: Could not find user wiki@wiki_history_extractor
```

For some reason it can't find the user on mongo, maybe it isn't created (?)

**Comment by frankjdelgado** [comment]
@testica 

- run `./environments/mongo/create_user.sh` 
- stop docker `docker-compose restart`

Let me know if that helps.

**Comment by testica** [comment]
Works... but what is the difference between `docker-compose up ` and `docker-compose restart` (?) with restart I cannot see the logs

**Comment by frankjdelgado** [comment]
@testica  `docker-compose restart` will run the  docker services as daemons. You can see the logs again if you run `docker-compose logs `

**Comment by testica** [comment]
gr8 m8 :+1:
